- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure Aditya user exists"
    user:
      name: amit
      state: present
  - name: "ensure Verma user exists"
    user:
      name: alex
      state: present
      
